stBM(1,"tree6575",[0,"","","menu/blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"menu/0609_f.gif","menu/0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","menu/titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"menu/titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"menu/titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"menu/titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"menu/back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Mensajería","php_mensajerialist.php?cmd=resetall"],"p1i0");
stIT("p1i2",["Contactos","php_contactolist.php?cmd=resetall"],"p1i0");
stIT("p1i3",["Clientes","#"],"p1i0");
stBS("p2",[],"p0");
stIT("p2i0",["Listado","php_clientelist.php?cmd=resetall"],"p1i0");
stIT("p2i1",["Avales",""],"p1i0");
stIT("p2i2",["Referencias",""],"p1i0");
stIT("p2i3",["Garantias",""],"p1i0");
stES();
stIT("p1i4",["Salir","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",["Elaborar nueva solicitud","php_solicitudadd_sel.php"],"p1i0");
stIT("p3i1",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",["Otorgar crédito","php_creditoadd.php"],"p1i0");
stIT("p4i1",["Listado","php_creditolist.php?cmd=resetall"],"p2i0");
stIT("p4i2",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p4i3",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stES();
stIT("p0i4",["       Pagos"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Realizar Pago","php_pagoadd.php"],"p1i0");
stIT("p5i1",["Realizar Pago Anticipado","php_pago_anticipadoadd.php"],"p1i0");
stIT("p5i2",["Listado","php_recibolist.php?cmd=resetall"],"p1i0");
stIT("p5i3",["Devoluciones","php_devolucionlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i5",["       Promotores"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",["Nuevo","php_promotoradd.php"],"p1i0");
stIT("p6i1",["Listado","php_promotorlist.php?cmd=resetall"],"p2i0");
stIT("p6i2",["Comisiones","php_promotor_comisionlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i6",["       Reportes"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",["Clientes",""],"p1i3");
stIT("p7i1",["Solicitudes",""],"p1i0");
stIT("p7i2",["Creditos",""],"p1i0");
stIT("p7i3",["Cobranza",""],"p1i0");
stIT("p7i4",["Cartera Vencida",""],"p5i1");
stIT("p7i5",["Contabilidad",""],"p1i0");
stES();
stIT("p0i7",["       Catálogos"],"p0i1");
stBS("p8",[],"p1");
stIT("p8i0",["Portafolio",""],"p1i0");
stIT("p8i1",["Usuarios",""],"p1i0");
stIT("p8i2",["Mensajeria",""],"p1i0");
stIT("p8i3",["Medios de Pago","php_medio_pagolist.php?cmd=resetall"],"p1i0");
stIT("p8i4",["Formas de Pago",""],"p1i0");
stIT("p8i5",["Estados Civiles","php_estado_civillist.php?cmd=resetall"],"p1i0");
stIT("p8i6",["Parentescos","php_parentesco_tipolist.php?cmd=resetall"],"p1i0");
stIT("p8i7",["Tipos de Vivienda","php_vivienda_tipolist.php?cmd=resetall"],"p1i0");
stIT("p8i8",["Formatos","php_formato_doctolist.php?cmd=resetall"],"p1i0");
stIT("p8i9",["Entidades Federativas","php_entidadlist.php?cmd=resetall"],"p1i0");
stIT("p8i10",["Delegaciones y Municipios","php_delegacionlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i8",[],"p0i0");
stES();
stEM();
