stBM(1,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Créditos"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Listado","php_creditolist.php?cmd=resetall"],"p1i0");
stIT("p2i1",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p2i2",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stIT("p2i3",["Cartera Vencida Despacho","php_cartera_vencidalist2.php"],"p1i0");
stIT("p2i4",["Creditos Incobrables","php_cartera_incobrablelist.php"],"p1i0");
stES();
stIT("p0i3",["       Reportes Contables"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p3i1",["Reporte Cartera Total","php_rpt_ct.php"],"p1i0");
stIT("p3i2",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p3i3",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p3i4",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p3i5",["Reporte Cartera Vig.","php_rpt_cv.php"],"p1i0");
stIT("p3i6",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p3i7",["Reporte TPCV"],"p3i5");
stIT("p3i8",["Reporte TPCVP"],"p3i6");
stIT("p3i9",["Reporte CC","php_rpt_cc.php"],"p1i0");
stIT("p3i10",["Reporte CVC","php_rpt_cvc.php"],"p1i0");
stES();
stIT("p0i4",[],"p0i0");
stES();
stEM();
