<table border="0" cellspacing="0" cellpadding="0" width="700" align="center">
     <tbody>
         <tr>
             <td colspan="2">            
              <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal">
              <span style="line-height: 115%; font-size: 9pt">
              <font face="Calibri">CONTRATO DE CREDITO SIMPLE CON INTERÉS DESCUENTO POR NÓMINA A LARGO PLAZO QUE CELEBRAN POR UNA PARTE <b style="mso-bidi-font-weight: normal">MICROFINANCIERA CRECE, S.A. DE C.V. SOFOM E.N.R.</b>, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ <b style="mso-bidi-font-weight: normal">“CREA”</b>  Y, POR LA OTRA,  $x_cliente Y QUE EN LO SUCESIVO SE LE DENOMINARÁ COMO<b style="mso-bidi-font-weight: normal">“EL ACREDITADO”</b> Y, QUE EN SU CONJUNTO SE LES DENOMINARÁ COMO <b style="mso-bidi-font-weight: normal">“LAS PARTES”</b>, DE CONFORMIDAD CON LAS SIGUIENTES DECLARACIONES Y CLÁUSULAS:</font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: center; margin: 0cm 0cm 10pt" class="MsoNormal" align="center"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">DECLARACIONES<o:p></o:p></font></span></b></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="margin: 0cm 0cm 10pt" class="MsoNormal"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">EL ACREDITADO DECLARA LO SIGUIENTE:<u><o:p></o:p></u></font></span></b></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal">
             <font face="Calibri">
             <b style="mso-bidi-font-weight: normal">
             <span style="line-height: 115%; font-size: 9pt">1.- </span>
             </b>
             <span style="line-height: 115%; font-size: 9pt">Ser persona física, mayor de edad, con domicilio en $x_direccion  y que cuenta con la capacidad legal para la celebración del presente contrato.<o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><font face="Calibri">2.-</font>
             </span></b><b style="mso-bidi-font-weight: normal"><span style="font-family: 'Times New Roman','serif'; font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"> </span></b><font face="Calibri"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">Que es su voluntad celebrar con <b>CREA</b> el presente Contrato, a efecto obtener en concepto de préstamo con interés la cantidad señalada en la cláusula Primera y de garantizar el puntual pago de la cantidad adeudada, así como de los intereses y demás accesorios legales que se puedan generar a favor de <b>CREA</b> y a su cargo.</span><span style="font-family: 'Times New Roman','serif'; font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">
             <o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: 'Times New Roman','serif'; font-size: 12pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"> </span><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">3.-</span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">Haber solicitado a <b>CREA</b> la apertura de un crédito simple con interés, el cual se describe en detalle en la Carátula del Contrato (en adelante "Crédito Simple”).</span><span style="font-family: 'Times New Roman','serif'; font-size: 12pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">4.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Los datos consignados en la Carátula del Contrato corresponden a los datos particulares del Crédito solicitado. <o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">5.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Que es empleado o trabajador y mantiene una relación laboral con la empresa que ha quedado señalada en la solicitud del contrato (el patrón), de quien recibe el pago de su nómina y que pretende seguir trabajando en dicha institución por el tiempo de la vigencia del presente contrato, situación que acredita con los documentos que se agregan al (y forman parte del) presente contrato como <b>anexo1</b>.<o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">6.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Que destinará el crédito para fines personales lícitos. <o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">7.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Declara bajo protesta de decir verdad que la información y toda clase de documentos presentados para la firma del presente contrato son de carácter lícito, y no carecen de validez alguna y autoriza a CREA a que corrobore la información de estimarlo necesario.<o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">8.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Previo a la firma del presente contrato, <b>CREA</b> le informó del CAT, el cual es el “Costo Anual Total de financiamiento expresado en términos porcentuales anuales que para fines informativos y de comparación, mismo que incorpora la totalidad de los costos y gastos inherentes del crédito por suscribir”, así como las características generales del crédito, información que ha sido aceptada y firmada por él, según consta la carátula de crédito del presente contrato, el cual forma parte integrante del mismo. <o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">9.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Da fé, que en el momento de la celebración del presente contrato, se le hace entrega de un ejemplar acompañado de todos sus anexos, que incluyen Carátula de crédito, tabla de amortización, solicitud de crédito,consentimiento de retención en nómina, Pagaré y descripción de referencias a artículos legales contenidas en el contrato, mismas que se podrán consultar de manera anexa al mismo (todos los documentos aquí descritos, el ACREDITADO los encontrará al final del presente contrato a excepción de la carátula la cual la encontrará al principio, los cuales son parte integrante del mismo). <o:p></o:p></span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 10pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">10.- </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><span style="mso-spacerun: yes"> </span>Previo a la firma del presente Contrato, <b>CREA</b> le explicó y le dio a conocer a su entera satisfacción antes de la firma del presente Contrato: (i) el contenido del mismo y de todos los documentos a suscribir, (ii) los cargos, el monto de las tasas de intereses y comisiones vigentes que cobra por cada uno de los conceptos previstos que se establecen en el presente Contrato, (iii) en su caso, los descuentos y bonificaciones que en su caso pudiera tener derecho, y (iv) que en caso de terminación o baja laboral con su actual Patrón, o que en caso de que por cualquier razón el patrón de <b>EL ACREDITADO</b> no logre retener el pago para depósito a CREA, o que CREA no de por recibido el pago de EL ACREDITADO  a través del patrón a su entera satisfacción, seguirá siendo obligación de EL ACREDITADO realizar los pagos correspondientes a este contrato, en el domicilio señalado por CREA para objetos del presente contrato. 
                   <o:p></o:p></span></font></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">CREA DECLARA LO SIGUIENTE:<o:p></o:p></font></span></b></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">1.-</span></b><span style="line-height: 115%; font-size: 9pt"> Ser una Sociedad Financiera de Objeto Múltiple, de nacionalidad Mexicana, legalmente constituida conforme a las leyes de la República Mexicana en los términos de la Escritura Pública No. 122,166, de fecha 19 de abril de 2007, pasada ante la fe del Notario Público No. 152 del Distrito Federal, Lic. Cecilio Gonzales Márquez, e inscrita en el Registro Público de Comercio con el Folio Mercantil No. 363745, de fecha 9 de Mayo de 2007.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">2.-</span></b><span style="line-height: 115%; font-size: 9pt"> Que su representante legal, el C. Javier Arturo Foncerrada Sánchez está debidamente facultado para celebrar el presente contrato, según consta en la Escritura Pública No. 122,166, de fecha 19 de abril de 2007, pasada ante la fe del Notario Público No. 152 del Distrito Federal, Lic. Cecilio Gonzales Márquez, e inscrita en el Registro Público de Comercio con el Folio Mercantil No. 363745, de fecha 9 de Mayo de 2007; manifestando bajo protesta de decir verdad, que hasta la fecha, no le han sido revocadas ni limitadas sus facultades en forma alguna.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">3.-</span></b><span style="line-height: 115%; font-size: 9pt"> Su domicilio fiscal y el domicilio asentado para cualquier tema relacionado para efectos del presente contrato, se encuentra ubicado en Boulevard Adolfo Ruiz Cortines 4302 Interior 212, Colonia Jardines Del Pedregal De San Ángel, Delegación Coyoacán, Ciudad De México C.P. 04500 <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">4.-</span></b><span style="line-height: 115%; font-size: 9pt"> Que en su objeto social, entre otros, contempla la facultad de otorgar créditos.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">5.-</span></b><span style="line-height: 115%; font-size: 9pt"> Que considerando las declaraciones de <b>EL ACREDITADO</b> es su voluntad otorgar un crédito simple con interés.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">6.-</span></b><span style="line-height: 115%; font-size: 9pt"> Que no requiere de autorización por parte de la Secretaría de Hacienda y Crédito Público para su constitución y operación como sociedad financiera de objeto múltiple, y se encuentra sujeta a la inspección y vigilancia de la Comisión Nacional Bancaria y de Valores, pero exclusivamente para verificar el cumplimiento de las disposiciones preventivas de lavado de dinero y financiamiento al terrorismo (Art. 95-Bis de la Ley General de Organizaciones y Actividades Auxiliares del Crédito).<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">7.-</span></b><span style="line-height: 115%; font-size: 9pt"> Que el presente Contrato fue inscrito ante el Registro de Contratos de Adhesión de la Comisión Nacional para la Defensa de los Usuarios de los Servicios Financieros, bajo el folio número: RECA: 1735-140-027143/02-06015-1117<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Expuestas las anteriores declaraciones, las partes que suscriben el presente contrato manifiestan su voluntad de otorgar y sujetarse al tenor de las siguientes:<o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: center; margin: 0cm 0cm 10pt" class="MsoNormal" align="center"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">CLAUSULAS<o:p></o:p></font></span></b></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">PRIMERA.-</span></b><span style="line-height: 115%; font-size: 9pt"> <b style="mso-bidi-font-weight: normal"><u>OBJETO DEL CONTRATO</u>.-</b> Sujeto a la firma del “Consentimiento de Retención”, CREA, otorga a EL ACREDITADO, un crédito simple con interés vía descuento de nómina, en moneda nacional (en lo sucesivo EL CRÉDITO SIMPLE), por un importe equivalente a $x_importe. <span style="mso-spacerun: yes"> </span>La citada cantidad, no comprende los intereses ordinarios, comisiones e impuestos y demás gastos que deba cubrir el cliente a favor de CREA de acuerdo a éste contrato. 
             <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">EL cliente dispondrá de la totalidad del crédito en una sola exhibición, mediante dispersión automática de fondos en cualquier banco que elija CREA, del cual EL ACREDITADO, se dará por recibido en la fecha que CREA abone a dicha cuenta.  <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso de que el crédito sea destinado para una reestructuración de deuda, CREA podrá total o parcialmente transferir los recursos a una tercera persona con la que EL ACREDITADO tenga un adeudo vigente. Para lo cual, CREA dispondrá de un comprobante de pago del adeudo.<o:p></o:p></font></span></p>
             </td>
         </tr>
         
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">SEGUNDA.-</span></b><span style="line-height: 115%; font-size: 9pt"> <b style="mso-bidi-font-weight: normal"><u>LUGAR Y FORMA DE PAGO</u>.-</b> <b>EL ACREDITADO</b> se obliga a pagar: <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">La cantidad señalada en la cláusula primera, los intereses ordinarios e intereses moratorios que se generen en virtud de lo pactado en el presente contrato, así como el Impuesto al Valor Agregado o cualquier impuesto que se encuentre vigente a la fecha en que se genere por causación de intereses u otros gastos. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><b>EL ACREDITADO</b> se obliga a pagar a <b>CREA</b>, de acuerdo a las obligaciones derivadas del presente Contrato, las cantidades convenidas sobre el Crédito Simple, las cuales se pagarán de su salario en forma quincenal de conformidad con el número de abonos y en los plazos estipulados en el “Consentimiento de Retención” que <b>EL ACREDITADO </b>solicite a su Patrón, documento que se agregará al presente Contrato y es parte integrante del mismo.<o:p></o:p></font></span></p> 
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Si por cualquier razón, el pago de la parcialidad no la pudo realizar el Patrón por cuenta y orden de <b>EL ACREDITADO, EL ACREDITADO</b> se compromete a pagar los abonos en el domicilio señalado por CREA, según los plazos estipulados en la Carátula del Contrato; o bien, <b>EL ACREDITADO</b> ofrecerá su consentimiento, para que se realice la domiciliación de dicho pago a la cuenta que el mismo proporcionó a <b>CREA</b> para tal efecto.<o:p></o:p></font></span></p>             
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Para el caso de que, por cualquier razón, el pago de la parcialidad por parte del Patrón por cuenta y orden de <b>EL ACREDITADO</b> se llegase a realizar por una cantidad menor a la convenida, se realice con un desfase mayor a 30 días naturales a la fecha en que corresponde cada amortización del crédito, o no se llegase a realizar por completo, en este acto <b>EL ACREDITADO</b>, manifiesta su conformidad para ampliar el número de abonos del presente Contrato, hasta en tanto, el saldo insoluto quede totalmente amortizado.  <o:p></o:p></font></span></p> 
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso de que el día en que <b>EL ACREDITADO</b> deba efectuar cualquier pago, fuere día inhábil, dicho pago se realizará el día hábil inmediato posterior al vencimiento correspondiente, lo anterior sin que proceda el cobro de comisiones o intereses moratorios  <o:p></o:p></font></span></p> 
            
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">TERCERA.-</span></b><span style="line-height: 115%; font-size: 9pt"> <b style="mso-bidi-font-weight: normal"><u>CONSENTIMIENTO DE RETENCIÓN</u>.- </b><span style="mso-spacerun: yes"> </span><b>EL ACREDITADO</b> en este acto acepta que mantendrá vigente el “Consentimiento de Retención” presentado al Patrón hasta que se cubran con el descuento a su nómina el total del crédito otorgado por <b>CREA</b> más sus accesorios.            <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><b>EL ACREDITADO</b> acepta que la Instrucción de Pago del crédito y sus accesorios vía el descuento de nómina de<b> EL ACREDITADO</b> sólo será suspendida hasta que el PATRÓN reciba un Aviso de parte de <b>CREA </b>donde se confirme al PATRÓN que <b>EL ACREDITADO</b> ha pagado el préstamo otorgado y sus accesorios en su totalidad.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso de que <b>EL ACREDITADO<b/> incumpla con lo estipulado en esta cláusula y solicite al Patrón dejar sin efectos los pagos correspondientes del descuento de su crédito de nómina conforme a lo estipulado en el “Consentimiento de retención” que entregó a su Patrón,<b> EL ACREDITADO</b> acepta que su patrón solo podrá llevar a cabo dicha solicitud una vez que reciba la solicitud o instrucción de parte de <b>CREA</b>, donde se indique que los adeudos de <b>EL ACREDITADO</b> han sido pagados en su totalidad. En caso de que <b>EL ACREDITADO</b> tenga un saldo por cubrir, <b>CREA</b> informará al patrón el adeudo que <b>EL ACREDITADO</b> tiene de su préstamo de nómina, y le indicará que la Instrucción de Pago deja de tener efecto hasta que quede cubierto dicho adeudo.<o:p></o:p></font></span></p>
           </td>
         </tr>
          <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">CUARTA.-</span></b><span style="line-height: 115%; font-size: 9pt"> <b style="mso-bidi-font-weight: normal"><u>INTERES ORDINARIO</u>.- </b><span style="mso-spacerun: yes"> </span>Las partes acuerdan que la cantidad de la clausula primera se le aplicara por concepto de interés ordinario una tasa fija del $x_anual_tasa en términos anuales.
                   <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Los intereses que se generen con motivo del presente contrato, deberán ser pagados por EL ACREDITADO dentro del día hábil inmediato siguiente a la semana transcurrida, y por la que se generó dicho interés, mientras el saldo del capital señalado en la cláusula primera se encuentre insoluto. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Los intereses se devengarán por quincenas vencidas, según sea el caso, a partir de la fecha de disposición del Crédito Simple. El cálculo de intereses se realizará de forma quincenal, multiplicando el saldo insoluto del Crédito simple por la tasa de interés mencionada al inicio de la presente cláusula. El resultado así obtenido, se dividirá entre 360 (trescientos sesenta) días y, a su vez, dicho resultado se multiplicará por $x_perio_pact. 
                   <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso de que, conforme a la Ley del Impuesto al Valor Agregado, EL ACREDITADO deba pagar  tal impuesto, o cualquier otro que a la fecha se encuentre vigente, deberán ser pagados a CREA conjuntamente con los intereses ordinarios generados.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">El pago de los intereses no podrá ser exigido por adelantado, sino únicamente por períodos vencidos<o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">QUINTA.-</span></b><span style="line-height: 115%; font-size: 9pt"> <b style="mso-bidi-font-weight: normal"><u>INTERES MORATORIO</u>.-</b>EL ACREDITADO se obliga a pagar a CREA intereses moratorios sobre cualquier cantidad vencida y no pagada del crédito, a una tasa moratoria igual al cincuenta por de un pago ordinario sobre cada uno de los vencimientos que presenten atraso.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> En caso de que, conforme a la Ley del Impuesto al Valor Agregado, EL ACREDITADO deba pagar tal impuesto o cualquier otro que a la fecha se encuentre vigente, deberán ser pagados a CREA conjuntamente con los intereses moratorios generados.    <o:p></o:p></font></span></p>
             </td>
         </tr>
         
         <tr>
             <td style="text-align: justify" colspan="2"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 9pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA"><strong>SEXTA.- <u>COMISIONES</u>.-</strong></span><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 9pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA"> Se le informa al ACREDITADO que no se cobrará ningún tipo de comisión, siendo únicamente los pagos descritos en las cláusulas cuarta y quinta del presente contrato.</span></td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">SEPTIMA.- <u> PAGOS ANTICIPADOS</u>.-</span></b><span style="line-height: 115%; font-size: 9pt"> Se entenderán por pagos anticipados, al pago parcial o total que aún no es exigible.</span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Cuando lo solicite <b>EL ACREDITADO</b>, <b>CREA</b> estará obligada a recibir pagos anticipados. Durante la vigencia del crédito, <b>EL ACREDITADO</b> podrá realizar pagos anticipados siempre y cuando esté al corriente de sus pagos exigibles y sean por una cantidad igual o mayor al pago que deba realizarse en el periodo correspondiente. Cuando el importe de los pagos anticipados no fuera suficiente para amortizar el saldo insoluto en su totalidad, <b>EL ACREDITADO</b> autoriza a <b>CREA</b> a que disminuya el número de pagos a realizar, asimismo <b>CREA</b> entregará a <b>EL ACREDITADO</b> una nueva tabla de amortización, lo anterior cada vez que <b>EL ACREDITADO</b> anticipe algún pago. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En el entendido de que el hecho que anticipe pagos parciales no le exime de la obligación de efectuar los pagos subsecuentes de acuerdo a la nueva tabla de amortización que CREA entregue a EL ACREDITADO,  y que en su momento se intergrará como un nuevo anexo al presente contrato.  <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Para los casos en que existan pagos anticipados, <b>CREA</b> calculará el importe de los intereses por devengar, con base en el nuevo saldo insoluto y le hará entrega a <b>EL ACREDITADO</b> del comprobante correspondiente al pago anticipado.        <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><b>EL ACREDITADO</b> podrá hacer pagos totales o parciales de manera anticipada, siempre que estos se realicen dentro del horario del área de Atención a Clientes de <b>CREA</b>; en caso contrario, los recursos se aplicarán el día hábil inmediato siguiente, con la consecuente actualización de los saldos a pagar.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso que<b> EL ACREDITADO</b> decida liquidar el crédito de manera anticipada, <b>CREA</b> únicamente cobrara el interés ordinario que se haya generado hasta la fecha en que se realice el pago total del mismo, más accesorios del crédito que en su caso y de acuerdo a las condiciones pactadas mediante éste contrato el crédito se hubiesen generado. <o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2"><p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">OCTAVA.- <u>DE LOS PAGOS EN EXCESO O INFERIORES A LOS ABONOS</u>.-</span></b><span style="line-height: 115%; font-size: 9pt"> En caso de que, en la fecha de pago,<b>CREA</b> reciba abono mayor al establecido en el presente Contrato, <b>EL ACREDITADO</b> podrá exigir el reembolso del pago en exceso a <b>CREA</b>.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En caso de que, en la fecha de pago, CREA reciba un abono por una cantidad menor a la establecida en el presente Contrato, será responsabilidad de EL ACERDITADO, realizar el pago por la diferencia en el domicilio señalado por CREA para efectos del presente contrato. <o:p></o:p></font></span></p>
           </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">NOVENA.-<u>ESTADO DE CUENTA</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">De conformidad con el artículo 23 de la Ley  para la Transparencia, EL ACREDITADO acepta realizar la consulta de su estado de cuenta de manera electrónica a través de la página <b>www.financieracrea.com</b> con el Usuario  y contraseña que ha sido entregado por personal facultado por CREA. Así mismo, bajo el consentimiento del presente contrato confirma que a la firma del presente instrumento, ha recibido el usuario y contraseña para poder hacer la consulta del mismo.<o:p></o:p></span></font></p>
 
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">El acreditado está de acuerdo y es consciente en cuenta que dicho estado de cuenta puede tardar hasta diez días hábiles en mostrar la información referente a un pago ú operación. Lo anterior, derivado del atraso que el patrón pueda tardar en informar a CREA acerca de las retenciones que se hubiesen realizado a EL ACREDITADO. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Los estados de cuenta contendrán al menos lo estipulado en el artículo 35 de las DISPOSICIONES DE CARÁCTER GENERAL en materia de transparencia aplicables a las Sociedades Financieras de Objeto Múltiple Entidades No Reguladas.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">La falta de recepción del estado de cuenta por cualquier circunstancia, no libera a <b>EL ACREDITADO</b> de su obligación de efectuar el pago correspondiente en la fecha límite de pago. <o:p></o:p></font></span></p>
              </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA.-<u>VIGENCIA.-</u></span></b><span style="line-height: 115%; font-size: 9pt"> La vigencia del presente contrato, será por el plazo estipulado en la Carátula del Contrato sin que sea prorrogable; fecha en la cual <b>EL ACREDITADO</b> deberá tener cubiertas todas y cada una de las obligaciones de pago derivadas de este Contrato; en caso contrario, el Contrato permanecerá vigente hasta en tanto <b>EL ACREDITADO</b> liquide totalmente y a satisfacción de <b>CREA </b>sus obligaciones de pago conforme al presente Contrato y al Pagaré.<o:p></o:p></span></font></p>
        
             </td>
         </tr>
         
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA PRIMERA. <u>PRELACION DE LOS PAGOS</u></span></b><span style="line-height: 115%; font-size: 9pt">.- <b>CREA</b> aplicará los pagos conforme al siguiente orden:<span style="mso-spacerun: yes">  </span>
               <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">1.-</span></b><span style="line-height: 115%; font-size: 9pt"> Intereses Moratorios. <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">2.-</span></b><span style="line-height: 115%; font-size: 9pt"> Intereses Ordinarios. <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">3.-</span></b><span style="line-height: 115%; font-size: 9pt"> Capital principal del Crédito otorgado.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En toda ocasión en que CREA aplique pagos tanto de intereses moratorios, así como intereses ordinarios; CREA cobrará la proporción de Impuesto al Valor Agregado, o cualquier otro impuesto que al momento y de acuerdo a la legislación aplicable se encuentre vigente. <o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA SEGUNDA. <u>CESIÓN DE DEUDA O CRÉDITO</u></span></b><span style="line-height: 115%; font-size: 9pt">.-EL ACREDITADO no podrá ceder total o parcialmente los derechos y obligaciones que le otorga el presente contrato.<span style="mso-spacerun: yes">  </span>
                   <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><b>CREA</b> queda facultada para ceder, total o parcialmente, o de cualquier otra manera negociar, los derechos del presente Contrato y/o el Pagaré, que lo documente de acuerdo a los términos y condiciones estipuladas en el artículo 299 y demás disposiciones aplicables de la Ley General de Títulos y Operaciones de Crédito, para lo cual<b> EL ACREDITADO</b> manifiesta expresamente su conformidad.<o:p></o:p></font></span></p>
           
             </td>
         </tr>
         
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA TERCERA. <u>TERMINACIÓN, RESCICIÓN Y/O VENCIMIENTO</u></span></b><span style="line-height: 115%; font-size: 9pt">.- Ambas partes aceptan que el presente contrato se dará por rescindido y/o por vencido anticipadamente y la cantidad entregada en préstamo será exigible en su totalidad más sus accesorios pactados en este contrato  en caso de los siguientes supuestos:       
               <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">a).-</span></b><span style="line-height: 115%; font-size: 9pt"> Cuando EL ACREDITADO no pague en forma oportuna una o varias de las amortizaciones de principal o intereses establecidas en el presente contrato. <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">b).-</span></b><span style="line-height: 115%; font-size: 9pt"> Si se comprobara la existencia de falsedad en la información o documentación proporcionada por EL ACREDITADO.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">c).-</span></b><span style="line-height: 115%; font-size: 9pt"> Si se comprobara que EL ACREDITADO destinara el monto proporcionado a un fin distinto a lo solicitado, y/o algún fin ilícito.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">d)-.</span></b><span style="line-height: 115%; font-size: 9pt"> Si ocurre alguna circunstancia extraordinaria que, a juicio de CREA, haga improbable que EL ACREDITADO no pueda cumplir con las obligaciones del presente contrato. <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">f)-.</span></b><span style="line-height: 115%; font-size: 9pt"> En caso de darse cualquier otro incumplimiento por parte de EL ACREDITADO en relación con el Crédito Simple en términos de este documento.<o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">g)-.</span></b><span style="line-height: 115%; font-size: 9pt"> No dar aviso en los términos de la claúsula décima novena de este contrato.<o:p></o:p></span></font></p>
 			<p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> En caso de actualizarse cualquiera de los supuestos mencionados, <b>CREA</b> podrá dar por vencido anticipadamente el Crédito Simple y demás accesorios estipulados en el presente instrumento y <b>EL ACREDITADO</b> deberá pagar a <b>CREA</b> de manera directa e inmediata el importe total del Saldo Insoluto del Crédito y todas las sumas que se adeuden bajo el presente Contrato. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> <b>EL ACREDITADO</b> podrá solicitar a <b>CREA</b> en cualquier momento durante la vigencia del presente contrato, la terminación anticipada del mismo, para lo cual deberá realizar dicha solicitud por escrito en las oficinas de <b>CREA</b>, y cubrir, en su caso, en los términos pactados en el presente contrato el monto total del adeudo, incluyendo todos los accesorios financieros que se hayan generado a la fecha en que solicite la terminación.<b> CREA</b>, verificará la identidad de <b>EL ACREDITADO</b> para la cual requerirá se adjunte la identificación oficial. Una vez recibida la solicitud, <b>CREA</b> le proporcionará a <b>EL ACREDITADO</b> el acuse de recibo y la clave de confirmación o número de folio de la recepción de la misma. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> En el caso de que no existan adeudos dará por terminado el contrato el día hábil siguiente a que reciba la solicitud de terminación. Si existen adeudos comunicará a <b>EL ACREDITADO</b> el monto de los adeudos el día hábil siguiente a la recepción de la solicitud y dentro los cinco días hábiles siguientes <b>CREA</b> pondrá a disposición de <b>EL ACREDITADO</b> el dato mencionado a determinada fecha en la sucursal elegida por el usuario y una vez cubierto el importe del adeudo, se dará por terminado al día siguiente.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> Al dar por terminada la relación contractual y en caso de que exista saldo a favor de <b>EL ACREDITADO, CREA</b> deberá entregarlo a dicho cliente en la fecha en que se dé por terminada la operación y en caso de que <b>EL ACREDITADO</b> no acuda a la sucursal u oficina de <b>CREA</b>, esta le informará que se encuentra a su disposición y le será devuelto mediante cheque expedido a su nombre o bien efectuando una transferencia electrónica de fondos a la cuenta bancaria de<b> EL ACREDITADO</b>, cuenta bancaria que éste haya indicado o indique en ese momento. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> <b>CREA</b> pondrá a disposición de <b>EL ACREDITADO</b> el documento en donde conste el fin de la relación contractual y la inexistencia de adeudos dentro de los diez días hábiles a partir de que se hubiere realizado el pago de los adeudos y reportará a las sociedades de información crediticia que la cuenta está cerrada sin adeudo alguno dentro del plazo que para tales efectos señala la Ley para Regular las Sociedades de Información Crediticia. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> Cuando la terminación del contrato sea por conducto de otra entidad financiera, esta liquidará el adeudo de <b>EL ACREDITADO</b> de acuerdo a la información que proporcione <b>CREA</b>, y una vez cubiertos los adeudos <b>CREA</b> renunciará a todos los derechos de cobro remanente que pudiera subsistir después del momento de la cancelación. <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> <b>EL ACREDITADO</b> podrá cancelar sin ninguna responsabilidad o comisión alguna a su cargo, el crédito objeto del presente contrato dentro de los 10 (diez) días hábiles posteriores a la firma del presente, siempre y cuando no haya recibido, utilizado o dispuesto del crédito, sin que CREA le cobre comisión alguna, conforme a lo señalado en el artículo 11 Bis 1 de la Ley para la Transparencia.  <o:p></o:p></font></span></p>
           </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA CUARTA. <u>DOMICILIOS Y NOTIFICACIONES.</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">Para los efectos de todas las notificaciones que sea necesario efectuar conforme al presente Contrato, las Partes señalan como sus domicilios los siguientes: 
                   <o:p></o:p></span></font></p>
                         <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> <B>EL ACREDITADO:</B> el declarado en la solicitud de crédito.<BR />
 <B>CREA:</B> Boulevard Adolfo Ruiz Cortines 4302 Interior 212, Colonia Jardines Del Pedregal De San Ángel, Delegación Coyoacán, Ciudad De México C.P. 04500. Cualquier cambio de domicilio deberá ser notificado por escrito a la otra Parte, y surtirá efectos a los 15 días siguientes a su recepción. Mientras no se reciba el aviso correspondiente, todas las comunicaciones enviadas al domicilio señalado se entenderán como válidas y surtirán plenos efectos legales.<o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2"><p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA QUINTA. <u>MEDIOS ELECTRÓNICOS</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">Las partes acuerdan el uso de equipos, medios electrónicos, ópticos o de cualquier otra tecnología, sistemas automatizados de procesamiento de datos y redes de telecomunicaciones, ya sean privados o públicos, para llevar a cabo operaciones, aclaraciones, notificaciones, solicitudes, autorizaciones, avisos y demás actos derivados de la celebración del presente Contrato. <B>CREA</B> proporcionará a <B>EL ACREDITADO </B>los medios de identificación necesarios para que este pueda utilizar estos medios. 
               <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><B>CREA</B> podrá suspender o cancelar el uso de equipos o medios de a que se refiere el párrafo anterior, cuando presuma que los medios de identificación pactados para tal efecto han sido utilizados en forma indebida. Lo anterior también resultará aplicable cuando detecte algún error en la instrucción respectiva.       <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En este acto, <B>EL ACREDITADO</B> autoriza a <B>CREA</B> para que pueda enviar toda clase de avisos, notificaciones, modificaciones al presente Contrato, promociones, publicidad, estados de cuenta e información adicional, ya sea por vía correo electrónico, mensajes de textos SMS y demás medios electrónicos ópticos o de cualquier otra tecnología que por avances tecnológicos faciliten las comunicaciones con <B>EL ACREDITADO</B>. Las disposiciones contenidas en el Título Segundo del Código de Comercio relativas al Comercio Electrónico le serán aplicables al presente Contrato.<o:p></o:p></font></span></p>
             </td>
         </tr>
       <tr>
             <td colspan="2">
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><font face="Calibri"><b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">DÉCIMA SEXTA. <u>PROCEDIMIENTO DE MODIFICACIÓN A LA AUTORIZACIÓN DEL ACREDITADO.-</u></span></b><span style="font-size: 9pt; mso-bidi-font-weight: bold; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"> </span><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><B>EL ACREDITADO</B> podrá revocar su decisión de negativa o autorización, respecto a la facultad de <B>CREA </B> para proporcionar sus datos personales a terceros con fines promocionales o de servicio, para lo cual enviará una carta con acuse de recibo notificando a <B>CREA</B> y/o sus afiliadas la nueva decisión.   </span></font></p>
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"> </p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><font face="Calibri"><b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">DÉCIMA SEPTIMA. <u> PRÁCTICAS DISCRIMINATORIAS.-</u> </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><B>CREA</B> no podrá realizar prácticas discriminatorias de cualquier índole, incluidos (i) los actos para no permitir la celebración de operaciones a <B>EL ACREDITADO </B>de otras entidades financieras o comerciales, (ii) el cobro de las comisiones distintas a las pactadas en el presente contrato y, (iii) los actos que se realicen para no permitir a <B>EL ACREDITADO</B> utilizar la infraestructura de otras entidades Financieras o desalentando su uso.</span></font></p>
             <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><o:p><font face="Calibri"> </font></o:p></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DECIMA OCTAVA. <u> EL ACREDITADO AUTORIZA A CREA A</u>.- </span></b><span style="line-height: 115%; font-size: 9pt"><BR />
               <B>a)</B> Proporcionar o recabar información sobre operaciones crediticias y de otra naturaleza análoga que haya celebrado con CREA.<BR />
 <B>b)</B> Permitir que CREA por conducto de cualquiera de sus representantes o persona que este designe, realice visitas a su domicilio y/o negocio para verificar el desarrollo de su actividad empresarial, así como también para efectos de gestionar cobranza en caso de que su cuenta presente atrasos vencidos.
 <BR /><B>c)</B> Llamar o enviar mensajes a sus domicilios o teléfonos celulares, o de cualquier otra forma, y en cualquier lugar para informar sobre los servicios que el CREA ofrece, así como para efectos de cobranza.
 <BR /><B>d)</B> Para que proporcionen la información otorgada por parte de EL ACREDITADO a aquellos prestadores de servicios operativos y de maquila que sean necesarios para la operación de los créditos.<span style="mso-spacerun: yes">  </span>
             <o:p></o:p></span></font></p>
             </td>
         </tr>
         <tr>
             <td colspan="2"><p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">DÉCIMA NOVENA. <u>SERVICIO, ATENCION AL CLIENTE Y REGULARIZACIÓN</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">Asimismo, de conformidad con lo previsto por la Ley para la Transparencia y Ordenamiento de los Servicios Financieros, la PARTES aceptan los siguientes términos respecto del presente:
             <o:p></o:p></span></font></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><B>CREA</B> pone a disposición de <B>EL ACREDITADO</B> una Unidad Especializada de Atención al Clientes, para atender cualquier duda ó queja en el siguiente No. Telefónico 55 51 35 02 59 dentro del DF y área metropolitana, así como el teléfono 01800 83 76 133 sin costo para el resto de la República Mexicana; y con dirección Boulevard Adolfo Ruiz Cortines 4302 Interior 212, Colonia Jardines Del Pedregal De San Ángel, Delegación Coyoacán, Ciudad De México C.P. 04500.    <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">El procedimiento para que EL ACREDITADO presente una aclaración y/o reclamación, es el siguiente:      <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"><B>EL ACREDITADO</B> deberá presentar la reclamación ante la <B>Unidad Especializada de Atención a Usuarios (UNE) de CREA.</B> En todos los casos, <B>CREA</B> estará obligada a acusar recibo de dicha solicitud.
 <B>Una vez recibida la solicitud de aclaración, CREA</B> tendrá un plazo máximo de cuarenta y cinco días para entregar a <B>EL ACREDITADO</B> el dictamen correspondiente, anexando copia simple del documento o evidencia considerada para la emisión de dicho dictamen, con base en la información que, conforme a las disposiciones aplicables, deba obrar en su poder, así como un informe detallado en el que se respondan todos los hechos contenidos en la solicitud presentada por <B>EL ACREDITADO</B>.    <o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">El dictamen e informe antes referidos deberán formularse por escrito y suscribirse por personal de <B>CREA</B> facultado para ello. En el evento de que, conforme al dictamen que emita la institución, resulte procedente el cobro del monto respectivo, <B>EL ACREDITADO </B>deberá hacer el pago de la cantidad a su cargo, incluyendo los intereses ordinarios conforme a lo pactado, sin que proceda el cobro de intereses moratorios y otros accesorios generados por la suspensión del pago realizada en términos de lo establecido en la presente cláusula. Dentro del plazo de cuarenta y cinco días naturales contado a partir de la entrega del dictamen a que se refiere el párrafo anterior, <B>CREA </B>estará obligada a poner a disposición de <B>EL ACREDITADO</B>, toda la documentación e información que, conforme a las disposiciones aplicables, deba obrar en su poder y que se relacione directamente con la solicitud de aclaración que corresponda y sin incluir datos correspondientes a operaciones relacionadas con terceras personas.<o:p></o:p></font></span></p>
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">En todo caso <B>EL ACREDITADO</B> deberá de agotar los procedimientos de autenticación solicitados por <B>CREA</B>. Cualquier aclaración, reclamación o consulta deberá de hacerse por escrito y hacerla llegar a <B>CREA</B> a su domicilio o por el medio que se le instruya. Asimismo, <B>CREA</B> hace del conocimiento de <B>EL ACREDITADO</B> el número telefónico de atención a usuarios de la Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros, para realizar cualquier queja: 5340 0999 ó LADA sin costo 01800 999 8080, mediante la página www.condusef.gob.mx ó mediante el correo electrónico <B>opinion@condusef.gob.mx</B>.    <o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">VIGÉSIMA. <u>TITULO EJECUTIVO</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">En términos del artículo 68 de la Ley de instituciones de Crédito, el presente Contrato junto con el Estado de Cuenta certificado expedido por el Contador debidamente autorizado por <b>CREA</b>, será título ejecutivo sin necesidad de reconocimiento de firma o de cualquier otro requisito, por lo que, en caso de incumplimiento por parte de <b>EL ACREDITADO</b> o en caso de vencimiento anticipado, <b>CREA</b> estará facultado para demandar en la vía ejecutiva mercantil o en la vía que más le convenga.<o:p></o:p></span></font></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">VIGÉSIMA PRIMERA. <u>MODIFICACIONES</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">Ninguna modificación de término o condición alguna del presente Contrato, y ningún consentimiento, renuncia o dispensa en relación con cualquiera de dichos términos o condiciones, tendrá efecto en caso alguno a menos que conste por escrito y esté suscrito por las partes y aún entonces dicha modificación, renuncia, dispensa o consentimiento sólo tendrá efecto para el caso y fin específicos para el cual fue otorgado. Lo anterior con excepción a las modificaciones realizadas a la información a que se refiere a comisiones y tasas de interés, por lo que éstas últimas no podrán ser modificadas durante la vigencia del presente contrato, salvo tratándose de reestructuras.
                   <o:p></o:p></span></font></p>
                         <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri"> De acuerdo al párrafo anterior, en caso de que por cualquier motivo <B>CREA</B> pretenda modificar el presente Contrato, deberá notificar dichos cambios a <B>EL ACREDITADO</B> mediante el envío con al menos 30 días naturales de anticipación a la fecha en que pretenda que dichas modificaciones surtan sus efectos, un aviso en el que se expliquen las modificaciones, dicho aviso se entregara en el domicilio pactado por <B>EL ACREDITADO</B> en este contrato. En caso de que después del aviso de modificación, <B>EL  ACREDITADO</B> no estuviera de acuerdo con los cambios propuestos, este podrá dar por terminado el presente Contrato, con hasta 30 (treinta) días posteriores al aviso donde se le notificaron las modificaciones; lo anterior sin responsabilidad alguna a su cargo, y bajo las condiciones pactadas originalmente, debiendo cubrir, en su caso, los adeudos que se generen hasta el término de la operación o el servicio, sin que <B>CREA</B> pueda cobrarle penalización alguna por dicha causa.<o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><font face="Calibri"><b style="mso-bidi-font-weight: normal"><span style="line-height: 115%; font-size: 9pt">VIGÉSIMA SEGUNDA. <u>LEGISLACIÓN APLICABLE Y JURISDICCIÓN</u>.-</span></b><span style="line-height: 115%; font-size: 9pt">Para todo lo relativo a la interpretación, ejecución y cumplimiento de este Contrato, las Partes se someten a la legislación aplicable y a la jurisdicción de los Tribunales compentes de la <U>Ciudad de México</U>, renunciando expresamente a cualquier otro fuero que pueda corresponderles por razón de sus domicilios presentes o futuros o por cualquier otra índole.            
             <o:p></o:p></span></font></p>
                         <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">El Presente Contrato y los datos de referencia consignados en el anverso, constituyen la expresión de la voluntad de las partes de quedar obligadas en los términos y condiciones aquí establecidas, por lo que se suscribe por <B>CREA</B> y/o sus afiliadas y <B>EL ACREDITADO</B>, en el lugar y fecha señalados. <o:p></o:p></font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><font face="Calibri"><b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">VIGÉSIMA TERCERA. <u>PAGARÉ.-</u> </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><B>EL ACREDITADO</B> suscribe en este acto un Pagaré, a la orden de <B>CREA, EL ACREDITADO </B> autoriza expresamente a <B>CREA</B> para descontar, ceder, endosar o de cualquier manera negociar el Pagaré, incluso antes de su vencimiento, el cual forma parte de los anexos del presentre contrato.</span></font></p>
            <br />
            </td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><font face="Calibri"><b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">VIGÉSIMA CUARTA. <u> INTEGRIDAD.-</u> </span></b><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX">Este contrato junto con sus anexos, solicitud contrato también llamada solicitud de crédito simple, Pagaré, consentimiento de retención, carátula del contrato de crédito simple y aviso de privacidad, representa el acuerdo total entre las partes, y dichos anexos se consideran parte integral del presente contrato.</span></font></p>
            
            <br /></td>
         </tr>
         <tr>
             <td colspan="2">
             <p style="text-align: justify; line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><font face="Calibri"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><b>EL ACREDITADO</b> manifiesta que <b>CREA</b> explicó a su entera satisfacción antes de la firma del presente contrato, el contenido del mismo y todos los documentos a suscribir, así como los cargos, comisiones o gastos que se generarán por su celebración. Asi mismo, manifiesta EL ACREDITADO haber recibido copia del presente contrato y todos los anexos descritos.</span></font></p>
             <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 9pt; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ES-MX"><o:p><font face="Calibri"> </font></o:p></span></p>
             </td>
         </tr>
         
       <tr>
             <td colspan="2">
             <p style="text-align: justify; margin: 0cm 0cm 10pt" class="MsoNormal"><span style="line-height: 115%; font-size: 9pt"><font face="Calibri">Se firma el presente contrato, en la Ciudad de México, el $x_fecha_contrato </font></span></p>
             </td>
         </tr>
         <tr>
             <td colspan="2"> </td>
         </tr>
         <tr>
             <td colspan="2"> </td>
         </tr>
         <tr>
             <td width="313" style="text-align: center"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 11pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA">EL ACREDITADO</span></td>
             <td width="387" style="text-align: center"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 11pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA">NOMBRE Y FIRMA DEL REPRESENTANTE LEGAL</span></td>
         </tr>
         <tr>
             <td> </td>
             <td> </td>
         </tr>
         <tr>
             <td> </td>
             <td> </td>
         </tr>
         <tr>
             <td style="text-align: center">______________________________</td>
             <td style="text-align: center">______________________________</td>
         </tr>
         <tr>
             <td style="text-align: center"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 11pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA">$x_cliente</span></td>
             <td style="text-align: left"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 11pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA"><b>MICROFINANCIERA CRECE, S.A. DE C.V. SOFOM.,</b><br /><b>E.N.R. (CREA).</b><br />Boulevard Adolfo Ruiz Cortines 4302 Interior 212,<br /> Colonia Jardines Del Pedregal De San Ángel, <br />Delegación Coyoacán,<br /> Ciudad De México C.P. 04500 </span></td>
         </tr>
         <tr>
             <td style="text-align: center"><span style="line-height: 115%; font-family: 'Calibri','sans-serif'; font-size: 11pt; mso-fareast-font-family: Calibri; mso-bidi-font-family: 'Times New Roman'; mso-fareast-language: EN-US; mso-ansi-language: ES-MX; mso-bidi-language: AR-SA"> </span></td>
             <td> </td>
         </tr>
        
        
         
     </tbody>
 </table>