stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["E-mail Oficial C","php_oficial_cumplimiento_mail.php?cmd=resetall"],"p1i0");
stIT("p1i2",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Elaborar nueva solicitud","php_solicitudadd_sel.php"],"p1i0");
stIT("p2i1",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stIT("p2i2",["Formato de Solicitud","php_solicitud_print_blank.php","_blank"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i1");
stIT("p3i1",["Liquidados","php_credito_liquidadolist.php?cmd=resetall"],"p1i0");
stIT("p3i2",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p3i3",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stIT("p3i4",["Cartera Vencida Despacho","php_cartera_vencidalist2.php"],"p1i0");
stIT("p3i5",["Creditos Incobrables","php_cartera_incobrablelist.php"],"p1i0");
stIT("p3i6",["Cartas de Mora","php_carta_moralist.php"],"p1i0");
stIT("p3i8",["Condonaciones","php_condonacionlist.php"],"p1i0");
stES();
stIT("p0i4",["       Pagos"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",["A. Masiva de pagos","php_aplicacion_pagos.php?cmd=resetall"],"p1i0");
stIT("p4i1",[,"php_recibolist.php?cmd=resetall"],"p2i1");
stIT("p4i2",["Pagos pendientes","php_masiva_pago_pendientelist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i5",["       Reportes Contables"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Cosechas","php_rpt_cosechas.php"],"p1i0");
stIT("p5i1",["Cosechas Cartera Total","php_rpt_cosechas_ct.php"],"p1i0");
stIT("p5i2",["Reporte de Vencidos","php_rpt_vencido.php"],"p1i0");
stIT("p5i3",["Reporte de Saldos","php_cartera_saldos_capital.php"],"p1i0");
stIT("p5i4",["Reporte de Devengados","php_rpt_devengados.php?cmd=resetall"],"p1i0");
stIT("p5i5",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p5i6",["Reporte Cartera Total","php_rpt_ct.php"],"p1i0");
stIT("p5i7",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p5i8",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p5i9",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p5i10",["Reporte Cartera Vig.","php_rpt_cv.php"],"p1i0");
stIT("p5i11",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p5i12",["Reporte TPCV"],"p5i10");
stIT("p5i13",["Reporte TPCVP"],"p5i11");
stIT("p5i14",["Reporte CC","php_rpt_cc.php"],"p1i0");
stIT("p5i15",["Reporte CVC","php_rpt_cvc.php"],"p1i0");
stES();
stIT("p0i6",["      Recibos de clientes"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",[,"php_recibo_qrlist.php?cmd=resetall"],"p2i1");
stES();
stIT("p0i7",["      Garantía líquida"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",[,"php_garantia_liquidalist.php?cmd=resetall"],"p2i1");
stES();
stIT("p0i8",["     Convenios"],"p0i1");
stBS("p8",[],"p1");
stIT("p8i0",["Convenio Liquidacion","php_convenio_liquidacionlist.php"],"p1i0");
stIT("p8i1",["Convenio Propuesta","php_convenio_propuesta.php"],"p1i0");
stIT("p8i2",["Convenio Orden","php_convenio_ordenlist.php"],"p1i0");
stES();
stIT("p0i9",["     Auditoria"],"p0i1");
stBS("p9",[],"p1");
stIT("p9i0",["Creditos otorgados","php_listado_creditos_otorgados_auditoria.php"],"p1i0");
stIT("p9i1",["Recibos QR","php_listado_recibos_qr_tesoreria.php"],"p1i0");
stIT("p9i2",[,"php_listado_convenio_liquidacion_semanal.php"],"p8i0");
stIT("p9i3",[,"php_listado_convenio_propuesta_semanal.php"],"p8i1");
stIT("p9i4",[,"php_listado_convenio_orden_semanal.php"],"p8i2");
stES();

stIT("p0i15",["       Facturacion"],"p0i1");
stBS("p15",[],"p1");
stIT("p15i2",["Archivos","php_factura_electronica_listado_archivo.php"],"p1i0");
stES();

stIT("p0i10",[],"p0i0");
stES();
stEM();
