stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["E-mail Oficial C","php_oficial_cumplimiento_mail.php?cmd=resetall"],"p1i0");
stIT("p1i2",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stIT("p2i1",["Galeria","php_galeria_fotograficalist.php","_blank"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i0");
stIT("p3i1",["Liquidados","php_credito_liquidadolist.php"],"p1i0");
stIT("p3i2",["Lista Nueva Vencidos","php_credito_vencido_list_new.php"],"p1i0");
stIT("p3i3",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stIT("p3i4",["Cartas de Mora","php_carta_moralist.php"],"p1i0");
stES();
stIT("p0i4",["       Estados de cuenta"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",["Imprimir masivo","php_credito_view_masivo2.php","_parent"],"p1i0");
stIT("p4i1",["Buscar cliente","php_listado_credito_view.php"],"p1i0");
stES();
stIT("p0i5",["       Catálogos"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Estados Civiles","php_estado_civillist.php?cmd=resetall"],"p1i0");
stIT("p5i1",["Parentescos","php_parentesco_tipolist.php?cmd=resetall"],"p1i0");
stIT("p5i2",["Tipos de Vivienda"],"p5i1");
stIT("p5i3",["Delegaciones","php_delegacionlist.php?cmd=resetall"],"p1i0");
stIT("p5i4",["Archivo muerto","php_direcciones_archivo_muerto.php"],"p1i0");
stES();
stIT("p0i6",["       Recibos Clientes"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",[,"php_recibo_qrlist.php?cmd=resetall"],"p2i0");
stES();
stIT("p0i7",["       Granatía Líquida"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",[,"php_garantia_liquidalist.php?cmd=resetall"],"p2i0");
stES();
stIT("p0i8",["      Convenios"],"p0i1");
stBS("p8",[],"p1");
stIT("p8i0",["Convenio Liquidación","php_convenio_liquidacionlist.php"],"p1i0");
stIT("p8i1",["Convenio Propuesta","php_convenio_propuesta.php"],"p1i0");
stIT("p8i2",["Convenio Orden","php_convenio_ordenlist.php"],"p1i0");
stES();
stIT("p0i9",["       Auditoria"],"p0i1");
stBS("p9",[],"p1");
stIT("p9i0",["Solicitudes","php_listado_documetos_solictudes.php"],"p1i0");
stIT("p9i1",["Créditos Otorgados","php_listado_creditos_otorgados_auditoria.php"],"p1i0");
stIT("p9i2",["Recibos QR","php_listado_recibos_qr_tesoreria.php"],"p1i0");
stIT("p9i3",[,"php_listado_convenio_liquidacion_semanal.php"],"p8i0");
stIT("p9i4",[,"php_listado_convenio_propuesta_semanal.php"],"p8i1");
stIT("p9i5",[,"php_listado_convenio_orden_semanal.php"],"p8i2");
stES();
stIT("p0i10",["      Cuadros Cartera"],"p0i1");
stBS("p10",[],"p1");
stIT("p10i0",["Cartera","php_cuadro_cartera.php"],"p1i0");
stIT("p10i1",["Dias sin pago","php_cuadro_dias_sin_pagar.php"],"p1i0");
stES();
stIT("p0i11",["      Reporte"],"p0i1");
stBS("p11",[],"p1");
stIT("p11i0",["Reporte de pagos","php_rpt_pagos.php"],"p1i0");
stES();
stIT("p0i12",[],"p0i0");
stES();
stEM();
