stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stIT("p2i1",["Galeria","php_galeria_fotograficalist.php"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i0");
stES();
stIT("p0i4",["      Comité de Crédito"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",["Iniciar comité","php_comite_de_credito.php"],"p1i0");
stIT("p4i1",[,"php_comite_de_credtiolist.php"],"p2i0");
stES();
stIT("p0i5",["       Reportes Contables"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Cosechas","php_rpt_cosechas.php"],"p1i0");
stIT("p5i1",["Reporte de Vencidos","php_rpt_vencido.php"],"p1i0");
stIT("p5i2",["Reporte de Saldos","php_cartera_saldos_capital.php"],"p1i0");
stIT("p5i3",["Reporte de Devengados","php_rpt_devengados.php?cmd=resetall"],"p1i0");
stIT("p5i4",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p5i5",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p5i6",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p5i7",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p5i8",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p5i9",["Reporte TPCV","php_rpt_cv.php"],"p1i0");
stIT("p5i10",["Reporte TPCVP"],"p5i8");
stIT("p5i11",["Reporte CC","php_rpt_cc.php"],"p1i0");
stIT("p5i12",["Reporte CVC","php_rpt_cvc.php"],"p1i0");
stES();
stIT("p0i6",["       Catalogos"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",["Estados Civiles","php_estado_civillist.php?cmd=resetall"],"p1i0");
stIT("p6i1",["Parentescos","php_parentesco_tipolist.php?cmd=resetall"],"p1i0");
stIT("p6i2",["Tipos de Vivienda"],"p6i1");
stIT("p6i3",["Delegaciones","php_delegacionlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i7",["       Zonas"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",["Asignar zonas","php_asigna_zona.php"],"p1i0");
stES();
stIT("p0i8",[],"p0i0");
stES();
stEM();
