stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Contactos","php_contactolist.php?cmd=resetall"],"p1i0");
stIT("p1i2",["Clientes","php_clientelist.php?cmd=resetall"],"p1i0");
stIT("p1i3",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Elaborar nueva solicitud","php_solicitudadd_sel.php"],"p1i0");
stIT("p2i1",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stIT("p2i2",["Formato de Solicitud","php_solicitud_print_blank.php","_blank"],"p1i0");
stIT("p2i3",["Galeria","php_galeria_fotograficalist.php"],"p2i2");
stES();
stIT("p0i3",["       Cr�ditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i1");
stIT("p3i1",["Liquidados","php_credito_liquidadolist.php"],"p1i0");
stIT("p3i2",["Fraude","php_credito_fraudelist.php?cmd=resetall"],"p1i0");
stIT("p3i3",["Lista Nueva Vencidos","php_credito_vencido_list_new.php"],"p1i0");
stIT("p3i4",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p3i5",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stIT("p3i6",["Cartera Vencida Despacho","php_cartera_vencidalist2.php"],"p1i0");
stIT("p3i7",["Creditos Incobrables","php_cartera_incobrablelist.php"],"p1i0");
stIT("p3i8",["Cartas de Mora","php_carta_moralist.php"],"p1i0");
stES();

stIT("p0i17",["       Garant�as L�quidas"],"p0i1");
stBS("p17",[],"p1");
stIT("p17i0",[,"php_garantia_liquida_listado_general.php"],"p2i1");
stIT("p17i1",["Pendientes","php_garantia_liquida_listado_pendientes.php"],"p1i0");
stIT("p17i2",["En Deuda","php_garantia_liquida_listado_deuda_garantia.php?cmd=resetall"],"p1i0");
stES();

stIT("p0i19",["       Comit� de Cr�dito"],"p0i1");
stBS("p19",[],"p1");
stIT("p19i0",[,"php_comite_de_creditolist.php?cmd=resetall"],"p2i1");
stIT("p19i1",["Iniciar Comit�","php_comite_de_credito.php"],"p1i0");
stES();

stIT("p0i4",["       Empresas"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",[,"php_empresalist.php"],"p2i1");
stES();
stIT("p0i5",["       Pagos"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["A. Masiva de pagos","php_aplicacion_pagos.php?cmd=resetall"],"p1i0");
stIT("p5i1",[,"php_recibolist.php?cmd=resetall"],"p2i1");
stIT("p5i2",["Pagos pendientes","php_masiva_pago_pendientelist.php?cmd=resetall"],"p1i0");
stIT("p5i3",["Recibos QR","php_recibo_qrlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i6",["       Promotores"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",["Nuevo","php_promotoradd.php"],"p1i0");
stIT("p6i1",[,"php_promotorlist.php?cmd=resetall"],"p2i1");
stIT("p6i2",["Comisiones","php_promotor_comisionlist.php?cmd=resetall"],"p1i0");
stIT("p6i3",["Responsables de sucursal","php_responsable_sucursallist.php?cmd=resetall"],"p1i0");
stIT("p6i4",["Vendedores","php_vendedorlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i7",["       Fondos"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",["Empresas","php_fondeo_empresalist.php?cmd=resetall"],"p1i0");
stIT("p7i1",["Creditos","php_fondeo_creditolist.php?cmd=resetall"],"p1i0");
stIT("p7i2",["Reporte de Restructuras","php_rpt_restructuras.php?cmd=resetall"],"p1i0");
stIT("p7i3",["Reporte de C. Riesgo","php_rpt_capital_riesgo.php?cmd=resetall"],"p1i0");
stIT("p7i4",["Reporte Clientes Finafim","php_clientelist_finafim.php"],"p1i0");
stIT("p7i5",["Reporte Cr�ditos Finafim","php_creditolist_finafim.php"],"p1i0");
stES();
stIT("p0i8",["       Reportes Contables"],"p0i1");
stBS("p8",[],"p1");
stIT("p8i0",["Cosechas","php_rpt_cosechas.php"],"p1i0");
stIT("p8i1",["Cosechas Cartera Total","php_rpt_cosechas_ct.php"],"p1i0");
stIT("p8i2",["Reporte de Vencidos","php_rpt_vencido.php"],"p1i0");
stIT("p8i3",["Reporte de Saldos","php_cartera_saldos_capital.php"],"p1i0");
stIT("p8i4",["Reporte de Devengados","php_rpt_devengados.php?cmd=resetall"],"p1i0");
stIT("p8i5",["Reporte de Devengados Historico","php_rpt_devengados_historico.php?cmd=resetall"],"p1i0");
stIT("p8i6",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p8i7",["Reporte Cartera Total","php_rpt_ct.php"],"p1i0");
stIT("p8i8",["Reporte Cartera Total Activa","php_rpt_ct_activos.php"],"p1i0");
stIT("p8i9",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p8i10",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p8i11",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p8i12",["Reporte Cartera Vig.","php_rpt_cv.php"],"p1i0");
stIT("p8i13",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p8i14",["Reporte TPCV"],"p8i10");
stIT("p8i15",["Reporte TPCVP"],"p8i11");
stIT("p8i16",["Reporte CC","php_rpt_cc.php"],"p1i0");
stIT("p8i17",["Reporte CVC","php_rpt_cvc.php"],"p1i0");
stIT("p8i18",["Reporte Circulo Cr�dito","php_circulocredito_rpt.php"],"p1i0");
stIT("p8i18",["Reporte Pagos Agrupados","php_rpt_pagos_bloques.php"],"p1i0");
stIT("p8i19",["Reporte Pagos Bloques","php_rpt_pagos_bloques_recibos.php"],"p1i0");
stES();
stIT("p0i9",["       Cat�logos"],"p0i1");
stBS("p9",[],"p1");
stIT("p9i0",["Usuarios","php_usuariolist.php?cmd=resetall"],"p1i0");
stIT("p9i1",["Medios de Pago","php_medio_pagolist.php?cmd=resetall"],"p1i0");
stIT("p9i2",["Estados Civiles","php_estado_civillist.php?cmd=resetall"],"p1i0");
stIT("p9i3",["Parentescos","php_parentesco_tipolist.php?cmd=resetall"],"p1i0");
stIT("p9i4",["Tipos de Vivienda"],"p9i3");
stIT("p9i5",["Formatos","php_formato_doctolist.php?cmd=resetall"],"p1i0");
stIT("p9i6",["Delegaciones","php_delegacionlist.php?cmd=resetall"],"p1i0");
stIT("p9i7",["Proceso Moratorios","php_pronoc.php"],"p2i2");
stIT("p9i8",["Bancos","php_bancolist.php?cmd=resetall"],"p1i0");
stIT("p9i9",["Archivo muerto","php_direcciones_archivo_muerto.php"],"p1i0");
stES();
stIT("p0i10",["       Gestores"],"p0i1");
stBS("p10",[],"p1");
stIT("p10i0",["Asignar casos","php_asigna_gestor.php"],"p1i0");
stES();
stIT("p0i11",["      Zonas"],"p0i1");
stBS("p11",[],"p1");
stIT("p11i0",["Asignar zonas","php_asigna_zona.php"],"p1i0");
stES();
stIT("p0i12",["      Convenios"],"p0i1");
stBS("p12",[],"p1");
stIT("p12i0",["Convenio Liquidaci�n","php_convenio_liquidacionlist.php"],"p1i0");
stIT("p12i1",["Convenio Propuesta","php_convenio_propuesta.php"],"p1i0");
stIT("p12i2",["Convenio Orden","php_convenio_ordenlist.php"],"p1i0");
stES();
stIT("p0i13",["      Auditoria"],"p0i1");
stBS("p13",[],"p1");
stIT("p13i0",["Solicitudes","php_listado_documetos_solictudes.php"],"p1i0");
stIT("p13i1",["Cr�ditos otorgados","php_listado_creditos_otorgados_auditoria.php"],"p1i0");
stIT("p13i2",[,"php_listado_recibos_qr_tesoreria.php"],"p5i3");
stIT("p13i3",[,"php_listado_convenio_liquidacion_semanal.php"],"p12i0");
stIT("p13i4",[,"php_listado_convenio_propuesta_semanal.php"],"p12i1");
stIT("p13i5",[,"php_listado_convenio_orden_semanal.php"],"p12i2");
stES();
stIT("p0i14",["       Cuadros cartera"],"p0i1");
stBS("p14",[],"p1");
stIT("p14i0",["Cartera","php_cuadro_cartera.php"],"p1i0");
stIT("p14i1",["Cartera PRONAFIM","php_cuadro_cartera_pronafim.php"],"p1i0");
stIT("p14i2",["Dias sin Pago","php_cuadro_dias_sin_pagar.php"],"p1i0");
stIT("p14i3",["Dias sin pago PRONAFIM ","php_cuadro_dias_sin_pagar_pronafim.php"],"p1i0");
stIT("p14i4",["DIFERENCIA ENTRE REPORTES","php_cuadro_cartera_diferencia.php"],"p1i0");
stES();
stIT("p0i15",["       Facturacion"],"p0i1");
stBS("p15",[],"p1");
stIT("p15i0",["Facturas","php_factura_listado_factura_por_mes.php"],"p1i0");
stIT("p15i1",["Notas de Credito","php_factura_listado_nota_por_mes.php"],"p1i0");
stIT("p15i2",["Archivos","php_factura_electronica_listado_archivo.php"],"p1i0");
stES();

stIT("p0i18",["       PLD"],"p0i1");
stBS("p18",[],"p1");
stIT("p18i0",["PPE","php_ppelist.php?cmd=resetall"],"p1i0");
stIT("p18i1",["OFAC","php_ofaclist.php?cmd=resetall"],"p1i0");
stIT("p18i2",["L.NEGRA CNBV","php_cnbvlist.php?cmd=resetall"],"p1i0");
stIT("p18i3",["Listado reporte CNBV","php_reporte_cnbvlist.php?cmd=resetall"],"p1i0");
stIT("p18i4",["ONU","php_onulist.php?cmd=resetall"],"p1i0");
stIT("p18i5",["Jurisdiccion","php_jurisdiccionlist.php?cmd=resetall"],"p1i0");
stIT("p18i6",["Revisar clientes","busca_OFAC_lista_negra.php?cmd=resetall"],"p1i0");
stIT("p18i7",["Tipo cambio","php_tipo_cambiolist.php?cmd=resetall"],"p1i0");
stIT("p18i8",["Grado Riesgo","php_puntajelist.php?cmd=resetall"],"p1i0");
stIT("p18i9",["Busqueda","php_busquedalistanegra.php"],"p1i0");
stES();




stIT("p0i16",[],"p0i0");
stES();
stEM();
