stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i0");
stIT("p3i1",["Lista Nueva Vencidos","php_credito_vencido_list_new_periodo.php"],"p1i0");
stIT("p3i2",["Lista Nueva Ven Periodo","php_credito_vencido_list_new.php"],"p1i0");
stIT("p3i3",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p3i4",["Cartera Vencida Despacho","php_cartera_vencidalist2.php"],"p1i0");
stIT("p3i5",["Creditos Incobrables","php_cartera_incobrablelist.php"],"p1i0");
stIT("p3i6",["Cartas de Mora","php_carta_moralist.php"],"p1i0");
stES();
stIT("p0i4",["       Reportes Contables"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",["Cosechas","php_rpt_cosechas.php"],"p1i0");
stIT("p4i1",["Cosechas Cartera Total","php_rpt_cosechas_ct.php"],"p1i0");
stIT("p4i2",["Reporte de Vencidos","php_rpt_vencido.php"],"p1i0");
stIT("p4i3",["Reporte de Saldos","php_cartera_saldos_capital.php"],"p1i0");
stIT("p4i4",["Reporte de Devengados","php_rpt_devengados.php?cmd=resetall"],"p1i0");
stIT("p4i5",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p4i6",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p4i7",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p4i8",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p4i9",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p4i10",["Reporte TPCV","php_rpt_cv.php"],"p1i0");
stIT("p4i11",["Reporte TPCVP"],"p4i9");
stES();
stIT("p0i5",["     Catalogos"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Localidad","php_catalogo_localidadlist.php"],"p1i0");
stIT("p5i1",["Tipo operacion","php_catalogo_tipo_operacionlist.php"],"p1i0");
stIT("p5i2",["Instrumento Monetario","php_catalogo_instrumento_monetariolist.php"],"p1i0");
stIT("p5i3",["Moneda o Divisa","php_catalogo_monedalist.php"],"p1i0");
stIT("p5i4",["Actividad Economica","php_catalogo_actividad_economicalist.php"],"p1i0");
stES();
stIT("p0i6",["     Gestor de casos"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",["Asignar Casos","php_asigna_gestor.php"],"p1i0");
stES();
stES();
stEM();
