stBM(2,"tree6575",[0,"","","blank.gif",0,"left","default","hand",1,0,28,201,-1,"none",0,"#666666","#eaedef","","repeat",1,"0609_f.gif","0609_uf.gif",9,9,0,"","","","",0,0,0,3,"right",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","#","_self","","","","",20,5,"8pt 'Arial'","#000000","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat","8pt 'Arial'","#0099FF","none","transparent","","repeat",1,0,"left","middle",0,0]);
stIT("p0i1",["       Menu Prinicpal",,,,,,,0,33,"bold 8pt 'Arial'",,,"#0099CC","titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif",,"bold 8pt 'Arial'","#000000",,,"titlebutton.gif"],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Inicio","php_inicio.php",,,,,,0,0,,,,,"back.gif",,,"#0000FF",,,,,,"#0000FF"],"p0i0");
stIT("p1i1",["Contactos","php_contactolist.php?cmd=resetall"],"p1i0");
stIT("p1i2",["Clientes","php_clientelist.php?cmd=resetall"],"p1i0");
stIT("p1i3",["Cerrar Sesion","logout.php"],"p1i0");
stES();
stIT("p0i2",["       Solicitudes"],"p0i1");
stBS("p2",[],"p1");
stIT("p2i0",["Elaborar nueva solicitud","php_solicitudadd_sel.php"],"p1i0");
stIT("p2i1",["Listado","php_solicitudlist.php?cmd=resetall"],"p1i0");
stIT("p2i2",["Formato de Solicitud","php_solicitud_print_blank.php","_blank"],"p1i0");
stES();
stIT("p0i3",["       Créditos"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",[,"php_creditolist.php?cmd=resetall"],"p2i1");
stIT("p3i1",["Cobranza","php_cobranzalist.php"],"p1i0");
stIT("p3i2",["Cartera Vencida","php_cartera_vencidalist.php"],"p1i0");
stIT("p3i3",["Cartera Vencida Despacho","php_cartera_vencidalist2.php"],"p1i0");
stIT("p3i4",["Creditos Incobrables","php_cartera_incobrablelist.php"],"p1i0");
stIT("p3i5",["Cartas de Mora","php_carta_moralist.php"],"p1i0");
stES();
stIT("p0i4",["       Pagos"],"p0i1");
stBS("p4",[],"p1");
stIT("p4i0",[,"php_recibolist.php?cmd=resetall"],"p2i1");
stES();
stIT("p0i5",["       Promotores"],"p0i1");
stBS("p5",[],"p1");
stIT("p5i0",["Nuevo","php_promotoradd.php"],"p1i0");
stIT("p5i1",[,"php_promotorlist.php?cmd=resetall"],"p2i1");
stIT("p5i2",["Comisiones","php_promotor_comisionlist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i6",["       Reportes Contables"],"p0i1");
stBS("p6",[],"p1");
stIT("p6i0",["Reporte de Devengados","php_rpt_devengados.php?cmd=resetall"],"p1i0");
stIT("p6i1",["Reporte de Pagos","php_rpt_pagos.php?cmd=resetall"],"p1i0");
stIT("p6i2",["Reporte Cartera Total","php_rpt_ct.php"],"p1i0");
stIT("p6i3",["Reporte CTP","php_rpt_ctp.php"],"p1i0");
stIT("p6i4",["Reporte TPCT","php_rpt_tpct.php"],"p1i0");
stIT("p6i5",["Reporte TPCTP","php_rpt_tpctp.php"],"p1i0");
stIT("p6i6",["Reporte Cartera Vig.","php_rpt_cv.php"],"p1i0");
stIT("p6i7",["Reporte CVP","php_rpt_cvp.php"],"p1i0");
stIT("p6i8",["Reporte TPCV"],"p6i6");
stIT("p6i9",["Reporte TPCVP"],"p6i7");
stIT("p6i10",["Reporte CC","php_rpt_cc.php"],"p1i0");
stIT("p6i11",["Reporte CVC","php_rpt_cvc.php"],"p1i0");
stIT("p6i12",["Reporte Circulo Crédito","php_circulocredito_rpt.php"],"p1i0");
stES();
stIT("p0i7",["       Catálogos"],"p0i1");
stBS("p7",[],"p1");
stIT("p7i0",["Usuarios","php_usuariolist.php?cmd=resetall"],"p1i0");
stIT("p7i1",["Medios de Pago","php_medio_pagolist.php?cmd=resetall"],"p1i0");
stIT("p7i2",["Estados Civiles","php_estado_civillist.php?cmd=resetall"],"p1i0");
stIT("p7i3",["Parentescos","php_parentesco_tipolist.php?cmd=resetall"],"p1i0");
stIT("p7i4",["Tipos de Vivienda"],"p7i3");
stIT("p7i5",["Formatos","php_formato_doctolist.php?cmd=resetall"],"p1i0");
stIT("p7i6",["Delegaciones","php_delegacionlist.php?cmd=resetall"],"p1i0");
stIT("p7i7",["Proceso Moratorios","php_pronoc.php"],"p2i2");
stIT("p7i8",["Bancos","php_bancolist.php?cmd=resetall"],"p1i0");
stES();
stIT("p0i8",[],"p0i0");
stES();
stEM();
