<?php

/**
 * General settings file.
 *
 */

// Database Settings

/*
$db_user = "megaex80_usu"; 					// Database username
$db_pass = "expopwd";					// Database password
$db_name = "expoco24_sswdbtest;			// Database name
$db_host = "localhost";					// Database host
$db_port = "3306";						// Database port
*/

/*
$db_user = "financ61_finusu"; 					// Database username
$db_pass = "creapwd";					// Database password
$db_name = "financ13_esf"; 				// Database name
$db_host = "localhost";					// Database host
$db_port = "3306";	*/					// Database port


$db_user = "financ13_admin61"; 			// Database username
$db_pass = "creapwd35961";					// Database password
$db_name = "financ13_esf"; 				// Database name


$db_host = "localhost";					// Database host
$db_port = "3306";						// Database port


// Parser settings

$parser_path = "../../";					// Path to Excel parser without /

?>